- name: Install httpd
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Enable and start httpd service
  ansible.builtin.service:
    name: "httpd"
    state: started
    enabled: true
