- hosts: yum
  become: true
  tasks:
    - name: Execute script
      script: files/uname/uname.sh
    - name: Install procps-ng
      ansible.builtin.package:
        name: 
          - procps-ng
          - passwd
        state: present
    - name: Execute commands in a shell
      shell: uptime && uname -a
      args:
        chdir: /tmp
      register: myoutput
      changed_when: myoutput.rc != 0
    - name: Execute command
      command: uname -a removes=/tmp/ejecutar
    - name: Install pexpect
      ansible.builtin.pip:
        name: pexpect
        state: present
    - name: Execute a command and respond to prompt
      expect: 
        command: passwd ansible
        responses: 
          (?i)password: "4ns1bL3-2023"
      become: true