- name: setting up DVWS container
  hosts: dind
  remote_user: "{{ remote_user_name }}"
  gather_facts: false
  become: true
  vars:
    remote_user_name: ansible
    dvws_image_name: cyrivs89/web-dvws
  tasks:
    - name: Install docker module
      ansible.builtin.pip:
        name: docker
        state: present
    - name: pulling {{ dvws_image_name }}
      docker_image:
        name: "{{ dvws_image_name }}"
        source: pull
    - name: running dvws container
      community.docker.docker_container:
        name: dvws
        image: "{{ dvws_image_name }}"
        interactive: true
        state: started
        ports:
          - "9980:80"