- name: Include tasks and import playbooks
  hosts: servers:&apt
  tasks:
    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present
      become: true
    - name: Include tasks
      ansible.builtin.include_tasks: tasks/include_apache2_tasks.yml

- name: Import playbook
  import_playbook: install_lftp_package.yml
