- name: First playbook
  hosts: apt:!ubuntu # TODO: Test on ubuntu
#  become: true
  tasks:
    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present
      become: true
    - name: Include tasks
      ansible.builtin.include_tasks: include_apache2_tasks.yml # TODO: Test this change

- name: Import playbook
  import_playbook: install_lftp_package.yml
