- name: First playbook
  hosts: apt:!ubuntu #TODO: Test on ubuntu
  #become: true
  tasks:
    - name: Install vim
      ansible.builtin.apt: 
        name: vim 
        state: present
      become: true
    - include: include_apache2_tasks.yml

- import_playbook: install_lftp_package.yml