- name: Install lftp package
  hosts: apt
  become: true
  tasks:
    - name: Update cache in debian family servers
      ansible.builtin.apt:
        update_cache: true
        name: lftp
        state: present
