- name: Lookup example
  hosts: servers:localhost
  tasks:
    - name: Lookup a file
      ansible.builtin.debug:
        msg: "{{ lookup('file', '/etc/motd') }}"

    - name: Lookup a file and store its content in a variable
      ansible.builtin.set_fact:
        etc_motd: "{{ lookup('file', '/etc/motd') }}"

    - name: Copy content to a remote file
      ansible.builtin.copy:
        dest: "/tmp/etc_motd"
        content: "{{ etc_motd }}"
        mode: 0644

    - name: Create a password
      ansible.builtin.set_fact:
        password: "{{ lookup('password', '/tmp/password.txt') }}"

    - name: Copy password to host
      ansible.builtin.copy:
        dest: "/tmp/copied_password"
        content: "{{ password }}"
        mode: 0400

    - name: Get cell from a csv file
      ansible.builtin.debug:
        msg: "{{ lookup('csvfile', 'row2 file=files/lookup/test.csv delimiter=, col=2') }}"

    - name: Get parameter from ini file
      ansible.builtin.debug:
        msg: "{{ lookup('ini', 'engine section=PHP file=files/lookup/test.ini') }}"

    - name: Install dnspython python library
      ansible.builtin.pip:
        name:
          - dnspython
        state: present
      become: true
      when: inventory_hostname == 'localhost'
    
    - name: Dig URL
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.dig', 'www.google.com') }}"

    - name: Dig MX record
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.dig', 'google.com/MX') }}"

    - name: Another way to dig MX record
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.dig', 'google.com', 'qtype=MX') }}"

    - name: Full MX records list
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.dig', 'google.com/MX', wantlist=true) }}"

    - name: Get env variable
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'PWD') }}"

    - name: Get file from template
      ansible.builtin.debug:
        msg: "{{ lookup('template', 'files/lookup/test.j2') }}"
