- name: Network config system modules
  hosts: alpines
  gather_facts: true
  tasks:
    - name: Show current hostname
      ansible.builtin.debug:
        var: ansible_hostname
    - name: Change hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}-new6"
      # TODO: No funciona el cambio de nombre pero tampoco da error en ubuntu
      # parece que solo funciona en alpine con --cap-add=SYS_ADMIN
      # TODO: Test if hostname works

    - name: Ping remote host
      ansible.builtin.ping:

    - name: Gather variables from remote host
      ansible.builtin.setup:

    - name: Show modified hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: Install iptables
      become: true
      ansible.builtin.package:
        name:
          - iptables
        state: present
    - name: Modify iptables rules
      become: true
      ansible.builtin.iptables:
        chain: INPUT
        source: 0.0.0.0
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Allow ip forwarding
      become: true
      ansible.posix.sysctl: # TODO: Test this change
        name: net.ipv4.ip_forward
        value: 1
        state: present
        sysctl_set: true
        reload: true
