- hosts: localhost
  connection: localhost
  vars:
    - notification_channel: "mail" # FIXME Test Slack and mail
    - email_address: "omrfloppy@gmail.com"
    - pushbullet_api_key: "o.2FbEyW4nyV2MHN2qdJcaqTIbNs509VfQ"
    - pushbullet_device: "Realme"
    - slack_token: "TAGRYDVGR/BAHLKF9SR/Xp9bqbsqLnqB5BmJxwigdUNo"
    - slack_channel: "#general"
  tasks:
  # TODO: docker run -d --rm --init --env POSTFIX_SMTP_HELO_NAME=localhost --env=POSTFIX_MYORIGIN=localhost --env=POSTFIX_MYHOSTNAME=localhost --name postfix --net ansible-net postfix:latest
    - name: "Notification by email"
      mail:
        host: postfix
        to: "{{ email_address }}"
        sender: root@localhost
        subject: "Task finished"
        body: "Task finished {{ ansible_fqdn }}"
      delegate_to: localhost
      when: notification_channel == "mail"

    - name: "Install pushbullet library"
      pip: 
        name: pushbullet.py
      when: notification_channel == "pushbullet"
    
    - name: "Notification by pushbullet"
      pushbullet:
        api_key: "{{ pushbullet_api_key }}"
        device: "{{ pushbullet_device }}"
        title: "Notification from {{ ansible_fqdn }}"
      when: notification_channel == "pushbullet"
    
    - name: "Notification by pushover"
      pushover:
        msg: "Notification from {{ ansible_fqdn }}"
        app_token: ""
        user_key: ""
      when: notification_channel == "pushover" 

    - name: Enviar notificacion a Rocket Chat
      rocketchat:
        token: ""
        domain: ""
        channel: ""
        msg: "{{ inventory_hostname }} completed"
        protocol: http
      delegate_to: localhost
      when: notification_channel == "rocketchat"
    
    - name: Enviar notificacion a Slack
      slack:
        token: "{{ slack_token }}"
        channel: "{{ slack_channel }}"
        msg: '{{ inventory_hostname }} completed'
      delegate_to: localhost
      when: notification_channel == "slack"