---
- name: Sample play to run a local script in a remote server
  become: true
  hosts: all 
  tasks:
    - name: "Run a local script on remote servers"
      ansible.builtin.script: files/script-module/uname.sh
      register: script_out

    - name: "Print script output"
      debug:
        msg: "{{ script_out }}"

- name: Other play to run a local script in a remote server
  hosts: all
  tasks:
    - name: "Run a local script on remote servers"
      ansible.builtin.script: files/script-module/my_script.sh
      register: script_out

    - name: "Print script output"
      debug:
        msg: "{{ script_out }}"