- name: Create file and fill it using a template and variables
  hosts: all
  vars: 
    - myip: "1.2.3.4"
  tasks:
    - name: Create hosts file
      template: src=templates/variables/hosts.j2 dest=/tmp/hosts