- hosts: all:!localhost
  tasks:
    - name: Wait for port 22 to be opened
      wait_for: 
        port: 22
        delay: 2
    - name: Wait until file exists
      wait_for: 
        path: /tmp/exists
    - name: Wait until file does not exist
      wait_for:
        path: /tmp/exists
        state: absent
